spring.application.name=libraryApp

# JDBC connection URL: jdbc:postgresql://[host]:[port]/[database-name] 
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}

# Replace with your actual PostgreSQL username and password 
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

# validate = Spring checks that your Entity classes match the DB schema on startup. 
# If they don't match, the app will refuse to start and show exactly what is wrong. 
# Other options: create(drop everything, recreate table on every run), create-drop(create oon start, drop pn shutdown), update(safely update schema), none(ddo nothing)
spring.jpa.hibernate.ddl-auto=validate 

# Print every SQL query to the Eclipse Console — very useful for debugging. 
# Set to false in production. 
spring.jpa.show-sql=false 

spring.jackson.property-naming-strategy=SNAKE_CASE
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false

# Tell Hibernate to use PostgreSQL-specific SQL syntax. 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.datasource.url — the JDBC connection string. 
#jdbc:postgresql://localhost:5432/librarydb tells Java to connect to PostgreSQL on the default port (5432) and open the librarydb database. 

#spring.jpa.hibernate.ddl-auto=validate — on startup, Hibernate compares every @Entity class to the live database schema. 
#If a column is missing or a name does not match, the app refuses to start and prints the exact problem. This catches mistakes early. 

#spring.jpa.show-sql=true — prints every generated SQL statement to the Eclipse Console. Invaluable for debugging. 

#spring.jpa.properties.hibernate.dialect — tells Hibernate to generate PostgreSQL-compatible SQL syntax.